volumes:
  postgres_data:
    driver: "local"
  maven_cache:

networks:
  wise_network:
    driver: "bridge"

services:
  postgres_schedule:
    image: postgres:alpine
    container_name: postgres_order_wise_compose
    restart: always
    environment:
      - POSTGRES_DB=wise
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - TZ=America/Sao_Paulo
    ports:
      - "5435:5432"
    networks:
      - wise_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: wise
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
        - wise_network

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: order_wise_backend_compose
    volumes:
      - maven_cache:/root/.m2
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8085:8085"
    networks:
      - wise_network